config/routes.rb
Cel::Application.routes.draw do

  root :to => 'home#index'

  ActiveAdmin.routes(self)
  resources :clients, :only => [:new, :create, :show]
  resources :pastors do 
		member do
			get 'pastor_events'
		end
	end
  resources :events do 
		member do
			post 'occurrence'
		end
	end
	resources :attendees
	resources :newsletters
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations"}
  mount Forem::Engine, :at => '/forums'

end

app/models/pastor.rb
class Pastor < ActiveRecord::Base
  belongs_to :user
  accepts_nested_attributes_for :user

  TITLES = [
		["Pastor", "Pastor"],
		["Preacher", "Preacher"],
		["Bishop", "Bishop"],
		["Minister", "Minister"],
		["Priest","Priest"]
	]



  has_attached_file :profile_pic, :styles => { :small => "150x100>", :medium => "400x400>", :large => "800x530>" }

  scope :active, where(:active => true)
  attr_accessible :address_one, :address_two, :bio, :email,
                  :name, :phone, :profile_pic, :active, :slug, :user,
                  :user_id, :title, :congregation, :user_attributes,
                  :is_active

  def to_s
  	"#{self.title} #{self.user.first_name}"
  end

	def self.search_for(params, current_user)
		pastors = []
		if params[:short_description_or_name].present?
			pastors = Pastor.joins(:user).where{}
			# Split the pastor. Let's see if there'e a title
			split_query = params[:short_description_or_name].split(" ")

			# This will need to go a bit deeper
			if self::TITLES.find_all{ |item| item[0] == split_query[0].capitalize }.any?
				denomination = split_query[0].capitalize
				pastors = pastors.where{ ( title =~ "%#{ my{ denomination } }%" ) }
				split_query.delete_at(0)
			end

			if split_query.length == 2
				# Assume first name and last name
				pastors = pastors.where{ (user.first_name =~ "%#{my{ split_query[0] }}%") | (user.last_name =~ "%#{my{ split_query[1] }}%") }
			end

			if split_query.length == 1
				# Assume just last name
				pastors = pastors.where{ (user.first_name =~ "%#{my{ split_query[0] }}%") | (user.last_name =~ "%#{my{ split_query[0] }}%") }
			end
		end
		pastors
	end
end

app/controllers/pastors_controller.rb
require 'json'

class PastorsController < InheritedResources::Base
	# before_filter :check_pastor_privileges!, only: [ :index ]
	before_filter :check_privileges!, only: [ :index ]

	def index
		# Check if user is a pastor and redirect to discourse app.
		# Otherwise show the login / create new pastor thing.
		@pastor = Pastor.new

		if current_user and current_user.pastor.present? and current_user.pastor.is_active
			redirect_to(forem.forums_url)
		else
			respond_to do |format|
				format.html
				format.json { render :json => @pastor }
			end
		end

	end

	def create
		@pastor = Pastor.new(params[:pastor])
		@pastor.user = current_user
		@pastor.is_active = true

		respond_to do |format|
			if @pastor.save
				format.html { redirect_to(@pastor, :notice => "Your account has been sucessfully created") }
				format.json { render :json => @pastor, :status => :created, :location => @pastor }
			else
				format.html { render :action => "new" }
				format.json { render :json => @pastor.errors, :status => :unprocessable_entity }
			end
		end
	end

	def show
		@pastor = Pastor.find(params[:id])
		@events = Event.where("user_id = ? AND is_occurrence = ?", @pastor.user.id, false)

		#if ! @events
			#@events = Array.new
		#end

		respond_to do |format|
			format.html
			format.json { render :json => [@pastor, @events] }
		end
	end

	def pastor_events
		start_date = DateTime.strptime(request.GET()[:start], "%s")
		end_date = DateTime.strptime(request.GET()[:end], "%s")
		@pastor = Pastor.find(params[:id])
		@events = Event.where("user_id = ? AND start_date >= ? AND start_date <= ?", @pastor.user.id, start_date, end_date)

		car = []
		for event in @events
			if event.is_occurrence
				color = "#3a87ad"
				event_path_string = ""
			else
				color = "#69a646	"
				event_path_string = event_path(event)
			end

			event_hash = { 
				:id => event.id, 
				:title => event.title,
				:start => event.start_date,
				:end => event.end_date,
				:url => event_path_string,
				:color => color
			}
			car << event_hash
		end

		respond_to do |format|
			format.json { render :json => car }
		end
	end
end

app/helpers/pastors_helper.rb
module PastorsHelper
end

app/views/pastors/_form.html.erb
<div class="row">
  <div class="span6">
    <div class="form-container">
      <%= semantic_form_for @pastor do |f| %>
        <%= f.inputs do %>
          <% if f.object.profile_pic.present? %>
            <%= image_tag(f.object.profile_pic.url(:small)) %>
          <% end %>
          <%= f.input :profile_pic, :as => :file %>
          <%= f.input :bio, :as => :ckeditor %>
          <%= f.input :phone %>
          <%= f.input :address_one %>
          <%= f.input :address_two %>
					<%= f.input :title, :as => :select, :collection => Pastor::TITLES %>
          <%= f.input :congregation %>
        <% end %>
        <%= f.actions do %>
          <%= f.action :submit, :as => :button,
                       :label => "Store changes",
                       :button_html => { :class => "btn btn-success" } %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/pastors/edit.html.erb
<div id="content">
	<div class="container">
		<%= render 'form' %>
	</div>
</div>

app/views/pastors/index.html.erb
<div id="content">
  <div class="container">
    <!-- Sign Up form -->
    <div class="row">
      <div class="span6 offset3">
        <% if current_user and current_user.pastor.present? %>
        <h1>You are already registered as a Pastor</h1>
        <% else %>
        <%= semantic_form_for @pastor, :html => { :class => "" } do |f| %>
        <h3 class="title-divider">
          <span>Register as a Pastor</span>
        </h3>
        <div>
          <%= f.inputs do %>
          <% if f.object.profile_pic.present? %>
          <%= image_tag(f.object.profile_pic.url(:small)) %>
          <% end %>
          <%= f.input :profile_pic, :as => :file, :input_html => { :class => "input-block-level" } %>
          <%= f.input :phone %>
          <%= f.input :address_one, :input_html => { :class => "input-block-level" } %>
          <%= f.input :address_two, :input_html => { :class => "input-block-level" } %>
          <%= f.input :title, :as => :select, :collection => Pastor::TITLES, :input_html => { :class => "input-block-level" } %>
          <%= f.input :congregation, :input_html => { :class => "input-block-level" } %>
          <% end %>
          <%= f.actions do %>
          <%= f.action :submit, :as => :button,
          :label => "Store changes",
          :button_html => { :class => "btn btn-success" } %>
          <% end %>
        </div>
        <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pastors/new.html.erb
<h1>New pastor</h1>

<%= render 'form' %>

<%= link_to 'Back', pastors_path %>

app/views/pastors/show.html.erb
<div id="content">
    <div class="container">

        <% if flash[:notice] %>
            <div class="alert alert-info">
                <%= flash[:notice] %>
            </div>
        <% end %>

        <!-- Services -->
        <div class="block features">
            <div class="row">
                <!-- Secondary features -->
                <div class="span9">
                    <h3 class="title-divider"><span><%= @pastor.title %><span class="de-em"><%= @pastor.user.get_full_name %></span></span>
                        <small><%= @pastor.user.first_name %> is the <%= @pastor.title %> of <%= @pastor.congregation %></small></h3>
                    <div class="tabbable tabs-left feature-tabs row-fluid">
                        <ul id="calendar-trigger" class="nav nav-tabs span4 hidden-phone">
                            <li class="active"> <a href="#tab1" data-toggle="tab">About  <small>Learn about <%= @pastor %></small><i class="icon-angle-right"></i></a> </li>
                            <li> <a href="#tab2" data-toggle="tab">Upcoming Events <small>Where will <%= @pastor %> be</small><i class="icon-angle-right"></i></a> </li>
                            <li><a href="#tab4" data-toggle="tab">My Calendar<small>Check my schedule</small><i class="icon-angle-right"></i></a></li>
                        </ul>
                        <div class="tab-content span8">
                            <div class="tab-pane active" id="tab1"> <%= image_tag @pastor.profile_pic.url(:medium) %> <br />
                                <h3 class="title visible-phone">Mobile Friendly</h3>
                                <!--only show on mobile when tabs are open-->
                                <%= raw @pastor.bio %>
                            </div>
                            <div class="tab-pane blog-roll blog-list" id="tab2">
                                <% for event in @events %>
                                <div class="media row-fluid <% if event.end_date < Date.today %>fade-out<% end %>">
                                    <div class="span2 hidden-phone">
                                        <!-- Date desktop -->
                                        <div class="date-wrapper">
                                            <span class="date-m"><%= event.start_date.strftime("%b") %></span>
                                            <span class="date-d"><%= event.start_date.day %></span>
                                        </div>
                                        <!-- Meta details desktop -->
                                        <p class="meta muted">
                                        <i class="icon-user"></i>

                                        <%= event_link_user(event) %>

                                        </p>
                                    </div>
                                    <div class="span10">
                                        <div class="media-body">
                                            <div class="tags">
                                                <a href="#" class="tag"><%= event.category.name %></a> / <a href="#" class="type"><%= event.tag_list %></a>
                                            </div>
                                            <h4 class="title media-heading">
                                                <!-- Meta details mobile -->
                                                <ul class="inline meta muted visible-phone">
                                                    <li><i class="icon-calendar"></i> <span class="visible-desktop">Starts:</span> <%= event.start_date %></li>
                                                    <li><i class="icon-user"></i> <%= event_link_user(event) %> </li>
                                                </ul>

                                                <% if event.published %>
                                                    <%= link_to event.short_description, event %>
                                                <% else %>
                                                    <%= event.short_description %>
                                                <% end %>
                                            </h4>
                                            <% if current_user == event.user %>
                                                <%= link_to "Edit", edit_event_path(event.id) %>
                                            <% end %>
                                            <!-- Meta details mobile -->
                                            <%= link_to image_tag(event.cover.url(:small)), event, :class => "media-object" %>
                                            <%= raw event.long_description[0, 500] %>
                                        </div>
                                    </div>
                                </div>
                            <% end %>
                            </div>
                            <div class="tab-pane" id="tab4" data-url="<%= pastor_events_pastor_path %>.json">
                                <div id="calendar_canvas"></div>
                                <% if user_signed_in? %>
                                <% if current_user.pastor and current_user.pastor == @pastor %>
                                    <div class="appointment-form">
                                        <h4>Add an occurrence to your calendar</h4>
                                        <%= form_tag(occurrence_event_path, :method => 'post') do %>
                                            <p>
                                            <%= text_field_tag(:title, nil, :placeholder => "Occurrence title") %>
                                            </p>
                                            <p>
                                            <%= text_field_tag(:start_date, nil, :placeholder => "Start date", :class => "datetimepicker") %>
                                            </p>
                                            <p>
                                            <%= text_field_tag(:end_date, nil, :placeholder => "End date", :class => "datetimepicker") %>
                                            </p>
                                            <p>
                                            <%= submit_tag("Create", :class => "btn btn-success", :name => nil) %>
                                            </p>
                                        <% end %>
                                    </div>
                                <% end %>
                                <% end %>
                            </div>
                        </div>
                    </div>
                </div>

                <!--Contact block-->
                <div class="span3">
                    <h3 class="title-divider"><span>Questions?</span> <small>Get in touch!</small></h3>
                    <p><abbr title="Phone"><i class="icon-phone"></i></abbr> <%= @pastor.phone %> </p>
                    <p><abbr title="Email"><i class="icon-envelope"></i></abbr> <%= @pastor.user.email %> </p>
                    <p><abbr title="Address"><i class="icon-home"></i></abbr> <%= @pastor.address_one %>, <%= @pastor.address_two %> </p>
                    <% if current_user != nil and current_user.is_admin or current_user == @pastor.user %>
                        <%= link_to "Edit", edit_pastor_path(@pastor.id) %>
                    <% end %>
                    <form id="contact-form" action="#" class="bordered-top-medium">
                        <input type="text" class="span2" placeholder="Your Number">
                        <input type="button" class="btn btn-inverse" value="Request A Callback">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>