config/routes.rb
Cel::Application.routes.draw do

  root :to => 'home#index'

  ActiveAdmin.routes(self)
  resources :clients, :only => [:new, :create, :show]
  resources :pastors do 
		member do
			get 'pastor_events'
		end
	end
  resources :events do 
		member do
			post 'occurrence'
		end
	end
	resources :attendees
	resources :newsletters
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations"}
  mount Forem::Engine, :at => '/forums'

end

app/models/client.rb
class Client < ActiveRecord::Base
	BANNER_SIZES = [
		["Large Full Banner", "Large Full Banner"],
		["2/3 Top", "2/3 Top"],
		["Top Banner", "Top Banner"],
		["Middle Banner", "Middle Banner"],
		["Bottom Banner", "Bottom Banner"]
	]

	STATES = Event::STATES

	has_attached_file :company_logo, :styles => { :small => "150x100>", :medium => "400x400>", :large => "800x530>" }
	has_attached_file :banner, :styles => { :small => "150x100>", :medium => "400x400>", :large => "800x530>" }

  attr_accessible :address_two, :address_one, :company, :email, :first_name,
  								:last_name, :phone, :website, :city, :state, :zip_code, :banner_size,
  								:banner, :company_logo
end

app/controllers/clients_controller.rb
class ClientsController < InheritedResources::Base
	def show
		redirect_to(root_path, :notice => "You message has been sent. Please wait for us to get in touch with you")
	end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= semantic_form_for @client do |f| %>
  <%= f.inputs do %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :company %>
    <%= f.input :website %>
    <%= f.input :email %>
    <%= f.input :phone %>
    <%= f.input :address_one %>
    <%= f.input :address_two %>
    <%= f.input :city %>
    <%= f.input :state, :as => :select, :collection => Client::STATES %>
    <%= f.input :zip_code %>

    <%= f.input :banner_size, :as => :select, :collection => Client::BANNER_SIZES %>

    <%= f.input :company_logo, :as => :file %>
    <%= f.input :banner_file_name, :as => :file %>

  <% end %>

  <%= f.actions do %>
		<%= f.action :submit, :as => :input, :input_html => { :class => "btn btn-success" } %>
  <% end %>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<h1>Listing clients</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Company</th>
    <th>Website</th>
    <th>Email</th>
    <th>Phone</th>
    <th>Address one</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clients.each do |client| %>
  <tr>
    <td><%= client.first_name %></td>
    <td><%= client.last_name %></td>
    <td><%= client.company %></td>
    <td><%= client.website %></td>
    <td><%= client.email %></td>
    <td><%= client.phone %></td>
    <td><%= client.address_one %></td>
    <td><%= link_to 'Show', client %></td>
    <td><%= link_to 'Edit', edit_client_path(client) %></td>
    <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<div id="content">
	<div class="container">
		<h2 class="title-divider">
			<span>Want to advertise with <span class="de-em">us?</span></span> <small>Give us some info and well get back to you</small>
		</h2>
		<div class="row-fluid">
			<div class="span4">
				<%= render 'form' %>
			</div>
			<div class="span8">
				<p>
				Christian Event Link allows any Christian Service to advertise site wide or for a specific event. Event banners are seen by people attending 
				events in your area and can help improve your Christian related business. In addition you can sponsor an event on 
				Christian Event Link and direct procedes to the event you are purchasing the ad for. We also offer site wide advertising and will 
				place your ad throughout Christian Event Link to advertise your business or your upcoming event
				</p>

				<p>
				Below are some standard banner advertisement sizes for events and site wide banner advertisements. 
				The sizes of the banners and placement can be selected in the dropdown menu at the left of the page. Please fill out the form and a 
				representative will get in touch with you to speak about pricing for each.
				</p>

				<div class="row">
					<div class="span4"><%= image_tag("banner23top.png") %></div>
					<div class="span4"><%= image_tag("adbanthird.png") %></div>
					<div class="span4"><%= image_tag("adbanfull.png") %></div>
				</div>

			</div>
		</div>
	</div>
</div>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @client.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @client.last_name %>
</p>

<p>
  <b>Company:</b>
  <%= @client.company %>
</p>

<p>
  <b>Website:</b>
  <%= @client.website %>
</p>

<p>
  <b>Email:</b>
  <%= @client.email %>
</p>

<p>
  <b>Phone:</b>
  <%= @client.phone %>
</p>

<p>
  <b>Address one:</b>
  <%= @client.address_one %>
</p>


<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>