config/routes.rb
Cel::Application.routes.draw do

  root :to => 'home#index'

  ActiveAdmin.routes(self)
  resources :clients, :only => [:new, :create, :show]
  resources :pastors do 
		member do
			get 'pastor_events'
		end
	end
  resources :events do 
		member do
			post 'occurrence'
		end
	end
	resources :attendees
	resources :newsletters
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations"}
  mount Forem::Engine, :at => '/forums'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "home"

	def index

	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="hero" id="highlighted">
	<% if flash[:notice] %>
      <div class="alert alert-info">
        <%= flash[:notice] %>
      </div>
  <% end %>
  <div class="inner">
    <!--Static Banner-->
    <section class="static-banner container">
      <div class="row-fluid">
        <div class="span5 caption">
          <h2 class="banner-copy">Welcome To Christian Event Link</h2>
          <p class="banner-copy">The perfect way to connect Christians with Christian Events!</p>
					<a href="<%= events_path %>" class="btn btn-large btn-success">Find Events</a>
        </div>
      </div>
    </section>
  </div>
</div>

<div id="content">
	<div class="container">
		<!-- Services -->
		<div class="block features">
            <h2 class="title-divider"><span>Get  <span class="de-em">Started</span></span> <small>
                    Christian Event Link is striving to improve the features and the functionality of our website every day.  This is the initial phase and there are more features to come.  Any suggestions or improvements are welcome as we are based in our users input for items that will improve how they find Christian based events.  To stay in touch with our updates please like us on facebook.
            </small></h2>
			<ul class="thumbnails">
				<li class="span3">
					<a href="<%= events_path %>">
						<%= image_tag("features/feature-1.png") %>
					</a>
					<h3 class="title">
						<%= link_to raw("Find <span class='de-em'>An Event / Pastor</span>"), events_path %>
					</h3>
					<p>
					Looking for Christian events in your area? We make your search quick and easy. You can even find local clergy in your area
					a click away!
					</p>
				</li>
				<li class="span3">
					<a href="<%= new_event_path %>">
						<%= image_tag("features/feature-2.png") %>
					</a>
					<h3 class="title">
						<%= link_to raw("Register <span class='de-em'>An Event</span>"), new_event_path %>
					</h3>
					<p>Want to let people know about your Event? With a few simples steps now you can!</p>
				</li>
				<li class="span3">
					<a href="<%= new_client_path %>">
						<%= image_tag("features/feature-3.png") %>
					</a>
					<h3 class="title"><a href="<%= new_client_path %>">Christian <span class="de-em">Services</span></a></h3>
					<p>Advertise Christians services to large groups of people seeking your specific offering.</p>
				</li>

				<li class="span3">
					<a href="<%= pastors_path %>">
						<%= image_tag("features/feature-4.png") %>
					</a>
					<h3 class="title">
						<a href="<%= pastors_path %>">
							Pastor <span class="de-em">Portal</span>
						</a>
					</h3>
					<p>Pastors, Preachers, Bishops, Ministers, Priest of all denominations and faiths receive specialized tools for communicating to followers.</p>
				</li>
		</ul>
	</div>

	<!--Pricing Table-->
	<div class="block">
		<div class="row-fluid">
			<!-- Plan features -->
			<div class="well well-mini pull-center">
				<h4 class="inline-el pad-right"><span>Register <span class="de-em">For Free</span>:</span></h4>
				<p class="inline-el pad-left muted">Free Event Registration <span class="spacer">//</span> Market Your Christian Services <span class="spacer">//</span> Free Event Search <span class="spacer">//</span></p>
			</div>
		</div>
	</div>

	<!--Customer testimonial-->
	<div class="block testimonials margin-top-large">
		<h2 class="title-divider"><span>Why Christian <span class="de-em">Event Link</span></span> <small>What are people saying about us!</small></h2>
		<div class="row">
			<div class="span4">
				<blockquote>
					<p>"It's totally awesome, we could not imagine life without it!"</p>
					<small>
						Vernon Whitaker <span class="spacer">/</span> <a href="#"></a>
					</small>
				</blockquote>
			</div>
			<div class="span4">
				<blockquote>
					<p>"10 out of 10, highly recommended!"</p>
					<small>

						Rick Carraway <span class="spacer">/</span> <a href="#"></a>
					</small>
				</blockquote>
			</div>
			<div class="span4">
				<blockquote>
					<p>"The best way on the web to find Christian Events"</p>
					<small>

						Shawn Pinkston <span class="spacer">/</span> <a href="#">Almond Development</a>
					</small>
				</blockquote>
			</div>
		</div>
	</div>
</div>
</div>