config/routes.rb
Cel::Application.routes.draw do

  root :to => 'home#index'

  ActiveAdmin.routes(self)
  resources :clients, :only => [:new, :create, :show]
  resources :pastors do 
		member do
			get 'pastor_events'
		end
	end
  resources :events do 
		member do
			post 'occurrence'
		end
	end
	resources :attendees
	resources :newsletters
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations"}
  mount Forem::Engine, :at => '/forums'

end

app/models/event.rb
class Event < ActiveRecord::Base
	extend FriendlyId
	friendly_id :title, :use => :slugged
  scope :unpublished, where(:published => false)

  STATES = [
    ['Alabama', 'AL'],
    ['Alaska', 'AK'],
    ['Arizona', 'AZ'],
    ['Arkansas', 'AR'],
    ['California', 'CA'],
    ['Colorado', 'CO'],
    ['Connecticut', 'CT'],
    ['Delaware', 'DE'],
    ['District of Columbia', 'DC'],
    ['Florida', 'FL'],
    ['Georgia', 'GA'],
    ['Hawaii', 'HI'],
    ['Idaho', 'ID'],
    ['Illinois', 'IL'],
    ['Indiana', 'IN'],
    ['Iowa', 'IA'],
    ['Kansas', 'KS'],
    ['Kentucky', 'KY'],
    ['Louisiana', 'LA'],
    ['Maine', 'ME'],
    ['Maryland', 'MD'],
    ['Massachusetts', 'MA'],
    ['Michigan', 'MI'],
    ['Minnesota', 'MN'],
    ['Mississippi', 'MS'],
    ['Missouri', 'MO'],
    ['Montana', 'MT'],
    ['Nebraska', 'NE'],
    ['Nevada', 'NV'],
    ['New Hampshire', 'NH'],
    ['New Jersey', 'NJ'],
    ['New Mexico', 'NM'],
    ['New York', 'NY'],
    ['North Carolina', 'NC'],
    ['North Dakota', 'ND'],
    ['Ohio', 'OH'],
    ['Oklahoma', 'OK'],
    ['Oregon', 'OR'],
    ['Pennsylvania', 'PA'],
    ['Puerto Rico', 'PR'],
    ['Rhode Island', 'RI'],
    ['South Carolina', 'SC'],
    ['South Dakota', 'SD'],
    ['Tennessee', 'TN'],
    ['Texas', 'TX'],
    ['Utah', 'UT'],
    ['Vermont', 'VT'],
    ['Virginia', 'VA'],
    ['Washington', 'WA'],
    ['West Virginia', 'WV'],
    ['Wisconsin', 'WI'],
    ['Wyoming', 'WY']
  ]

  AGE_GROUPS = {
    "Everyone" => "Everyone",
    "Under 15" => "Under 15",
    "15 to 24" => "15 to 24",
    "25 to 44" => "25 to 44",
    "45 to 64" => "45 to 64",
    "65 and up" => "65 and up"
  }

  just_define_datetime_picker :start_date, :add_to_attr_accessible => true
  just_define_datetime_picker :end_date, :add_to_attr_accessible => true
  just_define_datetime_picker :start_registration, :add_to_attr_accessible => true
  just_define_datetime_picker :end_registration, :add_to_attr_accessible => true

  belongs_to :user
  belongs_to :category
  has_many :attendees
  has_many :users, :through => :attendees

  acts_as_taggable

  validates_inclusion_of :age_group, :in => AGE_GROUPS

  has_attached_file :cover, :styles => { :small => "150x100>", :medium => "400x400>", :large => "540x340" }

  attr_accessible :address_one, :address_two, :state, :city, :contact_email, :contact_name,
  :contact_phone, :location, :long_description,
  :max_num_attendees, :min_num_attendees, :short_description,
  :zipcode, :tag_list, :custom_url, :video_url, :start_registration, :end_registration,
  :start_date, :end_date, :website, :facebook_url, :twitter_id, :twitter_hashtag,
  :minimum_age, :user, :user_id, :category_id, :age_group, :published, :cover, :title

	#def should_generate_new_friendly_id?
		#new_record?
	#end

  def self.search_for(params, current_user)
    events = Event.where{ (published == true) }
    if params[:short_description_or_name].present?
      events = events.joins(:user).where{
        (user.first_name =~ "%#{my{params[:short_description_or_name]}}%") | (user.last_name =~ "%#{my{params[:short_description_or_name]}}%") | (short_description =~ "%#{my{params[:short_description_or_name]}}%")
      }
    end

    if params[:category_id].present?
      events = events.joins(:category).where{
        (category.id = my{params[:category_id]})
      }
    end

    if params[:tags].present?
      events = events.tagged_with(params[:tags].split(","))
    end

    if params[:city].present?
      events = events.where{
        (city =~ "%#{my{params[:city]}}%")
      }
    end

    if params[:locale].present?
      events = events.where{
        (locale =~ "#{my{params[:locale]}}")
      }
    end

    if params[:zipcode].present?
      events = events.where{
        (zipcode = my{params[:zipcode]})
      }
    end

    if params[:start_date_from].present? and params[:start_date_to].present?
      from_date = DateTime.parse(params[:start_date_from])
      to_date = DateTime.parse(params[:start_date_to])
      events = events.find(:all, :conditions => { :start_date => from_date..to_date })
    elsif params[:start_date_from].present?
      from_date = DateTime.parse(params[:start_date_from])
      events = events.find(:all, :conditions => { :start_date => from_date })
    end

    if params[:mine].present? and current_user
      events = events.find(:all, :conditions => { :user_id => current_user.id })
    end
    events
  end
end

app/controllers/events_controller.rb
class EventsController < InheritedResources::Base
	before_filter :check_privileges!, only: [ :new, :create, :edit ]

	def index
		# TODO: Use metasearch or ransack next time. It's already installed but I need to move fast
		# or people in Nigeria will die!
		@events = Event.search_for(params, current_user)
		@pastors = Pastor.search_for(params, current_user)
		respond_to do |format|
    	format.html  # index.html.erb
	    format.json  { render :json => @events }
	  end
	end

	def new
		@event = Event.new
		respond_to do |format|
			format.html
			format.json { render :json => @event }
		end
	end

	def create
		# TODO: Remember the tag stuff
		@event = Event.new(params[:event])
		@event.user = current_user
		@event.start_date = DateTime.parse(params[:event][:start_date])
		@event.end_date = DateTime.parse(params[:event][:end_date])
		@event.published = false

		respond_to do |format|
			if @event.save
				format.html { redirect_to(@event, :notice => "Event creation was successful") }
				format.json { render :json => @event, :status => :created, :location => @event }
			else
				format.html { render :action => "new" }
				format.json { render :json => @event.errors, :status => :unprocessable_entity }
			end
		end
	end

	def occurrence
		@event = Event.new
		@event.user = current_user

		# Prepare dates

		@event.title = params[:title]

		@event.start_date = DateTime.parse(params[:start_date])
		@event.end_date = DateTime.parse(params[:end_date])

		@event.is_occurrence = true
		@event.save(:validate => false)

		redirect_to pastor_path(current_user.pastor)
	end
end

app/helpers/events_helper.rb
module EventsHelper
	def event_link_user(event)
		if event.user
			if event.user.pastor.present?
				link_to event.user.get_full_name, event.user.pastor
			else
				event.user.get_full_name
			end
		else
			"<DELETED>"
		end
	end

	def event_has_user(event)
		if event.user
			true
		else
			false
		end
	end
end

app/views/events/_attendees.html.erb
<% if @event.attendees %>
	<h3>People attending</h3>
	<div class="inner">
		<div class="block">
			<ul>
					<% for u in @event.users %>
                        <li>
                            <%= u %> 
                            <% if u == current_user %> 
                            <%= link_to "Cancel", @event.attendees.find_by_user_id(u.id), :method => :delete %> <% end %> 
                        </li>
					<% end %>
			</ul>
		</div>
	</div>
<% end %>

app/views/events/_description.html.erb
<h4>Step 1: Add event title</h4>
<%= f.input :title %>
<h4>Step 2: Add a brief description for listings and a category</h4>
<%= f.input :short_description, :label_html => { :class => "label label-defloater" } %>
<%= f.input :category, :include_blank => true %>
<h4>Step 3: Add a description for detail page</h4>
<%= f.input :long_description, :as => :ckeditor %>
<%= f.input :age_group, :collection => Event::AGE_GROUPS %>

app/views/events/_files.html.erb
<h4>Step 5: Upload a cover image</h4>
<%= f.input :cover, :as => :file %>
<% if @event.cover.present? %>
  <%= image_tag @event.cover.url(:small) %>
<% end %>

app/views/events/_form.html.erb
<%= semantic_form_for @event do |f| %>
  <%= f.inputs do %>
    <%= f.input :title %>
    <%= f.input :short_description %>
    <%= f.input :long_description %>
    <%= f.input :location %>
    <%= f.input :address %>
    <%= f.input :city %>
    <%= f.input :zipcode %>
    <%= f.input :contact_name %>
    <%= f.input :contact_email %>
    <%= f.input :contact_phone %>
    <%= f.input :start_date, :as => :string, :input_html => { :class => "datepicker" }  %>
    <%= f.input :end_date, :as => :string, :input_html => { :class => "datepicker" } %>
    <%= f.input :max_num_attendees %>
    <%= f.input :min_num_attendees %>
    <%= f.input :age_group, :as => :select, :collection => Event::AGE_GROUPS %>
    <%= f.input :start_registration, :as => :string, :input_html => { :class => "datepicker" } %>
    <%= f.input :end_registration, :as => :string, :input_html => { :class => "datepicker" } %>
    <% if f.object.cover %>
        <%= image_tag(f.object.cover.url(:small)) %>
    <% end %>
    <%= f.input :cover, :as => :file %>
    <%= f.input :category %>
  <% end %>
<% end %>

app/views/events/_host.html.erb
<h4>Step 7: Add a host</h4>

<%= f.input :contact_name %>
<%= f.input :contact_email %>
<%= f.input :contact_phone %>

app/views/events/_info.html.erb
	<h3>When and where</h3>
	<div class="inner">
		<div class="block">
			<ul>
				<li><strong><%= @event.location %></strong></li>
				<li><%= @event.address_one %>, <%= @event.address_two %></li>
				<li><%= @event.city %>, <%= @event.state %> <%= @event.zipcode %></li>
				<li><%= @event.start_date.strftime("%B %d, %y, at %I:%M %p") %></li>
				<li><%= @event.end_date.strftime("%B %d, %y, at %I:%M %p") %></li>
			</ul>
		</div>
	</div>
	<h3>Organizer</h3>
	<div class="inner">
		<div class="block">
			<ul>
				<li><strong><%= @event.contact_name %></strong></li>
				<li><%= @event.contact_email %></li>
				<li><%= @event.contact_phone %></li>
			</ul>
		</div>
	</div>

app/views/events/_location.html.erb
<h4>Step 6: Where</h4>
<%= f.input :location %>
<%= f.input :address_one %>
<%= f.input :address_two %>
<%= f.input :city %>
<%= f.input :state, :as => :select, :collection => Event::STATES %>
<%= f.input :zipcode %>

app/views/events/_search.html.erb
<div class="span3 sidebar sidebar-left">
  <h3>Search for Events</h3>
  <div class="inner">
    <div class="block">
      <%= form_tag(events_path, :method => "get") do %>
        <%= label_tag(:short_description_or_name, "Search Keywords") %>
        <%= text_field_tag(:short_description_or_name, nil, :placeholder => "Event name, Pastor") %>
        <%= label_tag(:category_id, "Category") %>
        <%= select_tag(:category_id, options_from_collection_for_select(Category.all, "id", "name"), :include_blank => true) %>
        <%= label_tag(:tags, "Tagged with") %>
        <%= text_field_tag(:tags, nil, :placeholder => "Tags separated by commas") %>

        <h5>Location</h5>
        <%= label_tag(:city, "City") %>
        <%= text_field_tag(:city) %>
        <%= label_tag(:location, "Locale") %>
        <%= text_field_tag(:location) %>
        <%= label_tag(:zipcode, "Zipcode") %>
        <%= text_field_tag(:zipcode) %>

        <h5>Date range</h5>
        <%= label_tag(:keywords, "From") %>
        <%= text_field_tag(:start_date_from, nil, :class => "datetimepicker") %>
        <%= label_tag(:keywords, "To") %>
        <%= text_field_tag(:start_date_to, nil, :class => "datetimepicker") %>

        <%= submit_tag("Search", :class => "btn btn-success", :name => nil) %>
      <% end %>
    </div>
    <!-- <div class="block"> <a href="#" class="btn btn-warning"><i class="icon-rss"></i> Subscribe via RSS feed</a> </div> -->
  </div>
</div>

app/views/events/_submit.html.erb
<div class="offset3" id="center-submit-button">
	<%= f.actions do %>
		<%= f.action :submit, :label => "Submit Event",
								 :as => :button, :button_html => { :class => "btn btn-success" } %>
	<% end %>
</div>

app/views/events/_time.html.erb
<h4>Step 4: When</h4>
<%= f.input :start_date, :as => :string, :input_html => { :class => "datetimepicker" } %>
<%= f.input :end_date, :as => :string, :input_html => { :class => "datetimepicker" }  %>

app/views/events/edit.html.erb
<div id="content">
  <div class="container">
    <%= semantic_form_for @event do |f| %>
      <%= f.inputs do %>
    <div class="row-fluid">
      <h2 class="title-divider"><span>Create an <span class="de-em">Event</span></span> <small>Follow the next simple steps</small></h2>
    </div>
    <div class="row">
      <div class="span6 blog-roll blog-list">
        <!-- Blog post -->
        <div class="media row-fluid">
          <div class="form-container">
            <%= render :partial => "events/description", :locals => { :f => f } %>
          </div>
          <div class="form-container">
            <%= render :partial => "events/time", :locals => {:f => f} %>
          </div>
        </div>
      </div>

      <!--Sidebar-->
      <div class="span6 sidebar sidebar-right">
        <div class="form-container">
          <%= render :partial => "events/files", :locals => {:f => f} %>
        </div>
        <div class="form-container">
          <%= render :partial => "events/location", :locals => {:f => f} %>
        </div>
        <div class="form-container">
          <%= render :partial => "events/host", :locals => {:f => f} %>
        </div>
      </div>
    </div>
    <% end %>
    <div class="row multiform-submit">
      <%= render :partial => "events/submit", :locals => { :f => f } %>
    </div>
  </div>
  <% end %>
  <!--.container-->
</div>

app/views/events/index.html.erb
<div id="content">
    <div class="container">
        <div class="row-fluid">
            <h2 class="title-divider">
                <span>Event <span class="de-em">listings</span></span>
                <!-- <small>We love to talk!</small> -->
            </h2>
        </div>
        <div class="row">
            <!--Sidebar-->
            <%= render 'events/search' %>

            <!--Blog Roll Content-->
            <div class="span9 blog-roll blog-list">
                <% if @pastors.any? %>
                    <div class="media row-fluid">
                        <h4>Pastors</h4>
                        <% for pastor in @pastors %>
                            <div class="span2">
                                <%= image_tag pastor.profile_pic.url(:small) %>
                                <p>
                                    <i class="icon-user"></i>
                                    <%= link_to pastor, pastor%>
                                </p>
                            </div>
                        <% end %>
                    </div>
                <% end %>

                <% @events.each do |event| %>
                    <h4>Events</h4>
                    <!-- Blog post -->
                    <div class="media row-fluid <% if event.end_date < Date.today %>fade-out<% end %>">
                        <div class="span1 hidden-phone">
                            <!-- Date desktop -->
                            <div class="date-wrapper">
                                <span class="date-m"><%= event.start_date.strftime("%b") %></span>
                                <span class="date-d"><%= event.start_date.day %></span>
                            </div>
                            <!-- Meta details desktop -->
                            <p class="meta muted">
                            <i class="icon-user"></i>

                            <%= event_link_user(event) %>

                            </p>
                        </div>
                        <div class="span11">
                            <div class="media-body">
                                <div class="tags"><a href="#" class="tag"><%= event.category.name %></a> / <a href="#" class="type"><%= event.tag_list %></a></div>
                                <h4 class="title media-heading">
                                    <!-- Meta details mobile -->
                                    <ul class="inline meta muted visible-phone">
                                        <li><i class="icon-calendar"></i> <span class="visible-desktop">Starts:</span> <%= event.start_date %></li>
                                        <li><i class="icon-user"></i> <%= event_link_user(event) %> </li>
                                    </ul>

                                    <%= link_to event.short_description, event %>
                                </h4>
                                <% if current_user == event.user %>
                                    <%= link_to "Edit", edit_event_path(event.id) %>
                                <% end %>
                                <!-- Meta details mobile -->
                                <%= link_to image_tag(event.cover.url(:small)), event, :class => "media-object" %>

                                <p>
                                <%= raw event.long_description[0, 500] %>...
                                </p>

                                <ul class="inline links">
                                    <li>
                                    <!--  <a href="blog-post.htm" class="btn btn-mini">
                                        <i class="icon-circle-arrow-right"></i> Read more
                                    </a> -->
                                    <%= link_to raw("<i class='icon-circle-arrow-right'></i>Read more..."), event, :class => "btn btn-mini" %>
                                    </li>
                                    <!-- <li>
                                    <a href="blog-post.htm#comments" class="btn btn-mini"><i class="icon-comment"></i> 50 Comments</a>
                                    </li> -->
                                </ul>
                            </div>
                        </div>
                    </div>
                <% end %>

                <div class="pagination pagination-centered">
                    <button type="button" class="btn btn-block" data-loading-text="Loading...">Load More</button>
                </div>

            </div>
        </div>
    </div>
    <!--.container-->
</div>

app/views/events/new.html.erb
<div id="content">
  <div class="container">
    <%= semantic_form_for @event do |f| %>
      <%= f.inputs do %>
    <div class="row-fluid">
      <h2 class="title-divider"><span>Create an <span class="de-em">Event</span></span> <small>Follow the next simple steps</small></h2>
    </div>
    <div class="row">
      <div class="span6 blog-roll blog-list">
        <!-- Blog post -->
        <div class="media row-fluid">
          <div class="form-container">
            <%= render :partial => "events/description", :locals => { :f => f } %>
          </div>
          <div class="form-container">
            <%= render :partial => "events/time", :locals => {:f => f} %>
          </div>
        </div>
      </div>

      <!--Sidebar-->
      <div class="span6 sidebar sidebar-right">
        <div class="form-container">
          <%= render :partial => "events/files", :locals => {:f => f} %>
        </div>
        <div class="form-container">
          <%= render :partial => "events/location", :locals => {:f => f} %>
        </div>
        <div class="form-container">
          <%= render :partial => "events/host", :locals => {:f => f} %>
        </div>
      </div>
    </div>
    <% end %>
    <div class="row multiform-submit">
      <%= render :partial => "events/submit", :locals => { :f => f } %>
    </div>
  </div>
  <% end %>
  <!--.container-->
</div>

app/views/events/show.html.erb
<div id="content">
    <div class="container">
        <div class="row-fluid">
            <h2 class="title-divider">
                <span>Event <span class="de-em">Listing</span></span>
                <small>
                    <%= link_to raw("<i class='icon-arrow-left'></i>Back to listings"), events_path %>
                </small>
            </h2>
        </div>
        <div class="row">
            <!--Sidebar-->
						<div class="span3 sidebar sidebar-left">
							<%= render "events/info" %>
							<%= render "events/attendees" %>
						</div>
            <!--Main Content-->
            <div class="span9 blog-post">

                <!-- Blog post -->
                <div class="media row-fluid">
                    <div class="span1 hidden-phone">
                        <!-- Date desktop -->
                        <div class="date-wrapper">
                            <span class="date-m"><%= @event.start_date.strftime("%b") %></span>
                            <span class="date-d"><%= @event.end_date.day %></span>
                        </div>
                        <!-- Meta details desktop -->
                        <p class="meta muted">
                        <i class="icon-user"></i>

                        <%= event_link_user(@event) %>

                        </p>
                    </div>
                    <div class="span11">
                        <div class="media-body">
                            <div class="tags">
                                <a href="#" class="tag"><%= @event.category.name %></a> / <a href="#" class="type"><%= @event.tag_list %></a>
                            </div>

														<div class="social-media">
															<div id="fb-root"></div>
															<script>(function(d, s, id) {
																var js, fjs = d.getElementsByTagName(s)[0];
																if (d.getElementById(id)) return;
																js = d.createElement(s); js.id = id;
																js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=429161183839650";
																fjs.parentNode.insertBefore(js, fjs);
															}(document, 'script', 'facebook-jssdk'));</script>
															<script src="http://static.ak.fbcdn.net/connect.php/js/FB.Share" type="text/javascript"></script>

															<a name="fb_share" type="button" href="http://www.facebook.com/sharer.php">Share</a>
															<span style="display:block; margin-top: 10px;">
															<div class="fb-like" data-send="true" data-width="450" data-show-faces="false" data-action="recommend"></div>
															</span>
														</div>

                            <h3 class="title media-heading"><%= @event.short_description %></h3>
                            <% if current_user != nil and current_user == @event.user %>
                                <%= link_to "Edit", edit_event_path(@event.id) %>
                            <% end %>

                            <!-- Meta details mobile -->
                            <ul class="inline meta muted visible-phone">
                                <li><i class="icon-calendar"></i> <span class="visible-desktop">Starts:</span> <%= @event.start_date %> </li>
                                <li><i class="icon-user"></i> <a href="#"> @event.user.get_full_name </a></li>
                            </ul>

                            <div class="media-object">
                                <%= image_tag @event.cover.url(:large) %>
                            </div>
                            <p class="lead">
                            <%= @event.short_description %>
                            </p>

                            <p>
                            <%= raw @event.long_description %>
                            </p>
                            <% if current_user %>
                                <p>
                                <% if ! @event.users.include? current_user %>
                                    <%= form_tag(attendees_path, :method => "post") do %>
                                        <%= hidden_field_tag :user_id, current_user.id %>
                                        <%= hidden_field_tag :event_id, @event.id %>
                                        <%= submit_tag nil, :value => "Attend event", :class => "btn btn-success" %>
                                    <% end %>
                                <% end %>
                                </p>
                            <% end %>
                        </div>
                        <div id="disqus_thread"></div>
                        <script type="text/javascript">
                            /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
                            var disqus_shortname = 'christianeventlink'; // required: replace example with your forum shortname

                            /* * * DON'T EDIT BELOW THIS LINE * * */
                            (function() {
                                 var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                                 dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                                 (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
                             })();
                        </script>
                        <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                        <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>